### Read all films
@baseUrl = http://localhost:3000
GET {{baseUrl}}/films

### Read  all films with filter
GET {{baseUrl}}/films?minimum-duration=190

### Read the film identified by an id 
GET {{baseUrl}}/films/3

### Add new film 
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title":"Inglorius Bastards",
    "duration": 153 , 
    "budget": 70000000,
    "link": "https://en.wikipedia.org/wiki/Inglourious_Basterds"
}